//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditTaskMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reseller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reseller()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public string reseller_id { get; set; }
        public string reseller_name { get; set; }
        public string reseller_contact_person { get; set; }
        public string reseller_address { get; set; }
        public string reseller_email { get; set; }
        public string reseller_phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
